# DB 생성 및 수정 필수!

spring:
  datasource:
    url: jdbc:mysql://192.168.100.174:3306/food?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: board
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mappers/**/*.xml
  type-aliases-package: kr.map.food.domain